name: webscrap
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy<2.0
  - biopython<=1.79
  - networkx<3.0
  - protobuf<5.0
  - matplotlib
  - scikit-learn
  - requests
  - spacy
  - pip
  - pip:
    - scispacy
    - sentence-transformers
